const mongoose=require("mongoose");

const userSchema=new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true
    },
    lastName:{
        type:String,
        required:true,
        trim:true
    },
    shopName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true,
    },
    shopAddress:{
        type:String,
        required:true,
        trim:true
    },
    contactNumber:{
        type:Number,
        required:true,
        trim:true
    },
    grocery:[
        {
        type:mongoose.Schema.Types.ObjectId,
        ref:"Grocery"
    }
],
   accountType:{
    type:String,
    enum:["Customer","WholeSaler","Admin"],
    required:true
   }
},
{timestamps:true}
);

module.exports=mongoose.model("User",userSchema)
